fastcgi_param Host $host;
fastcgi_param X-Real-IP $remote_addr;
fastcgi_param X-Forwarded-Proto https;
fastcgi_param X-Forwarded-For $proxy_add_x_forwarded_for;

fastcgi_connect_timeout 10s;
fastcgi_send_timeout 60s;
fastcgi_read_timeout 60s;

fastcgi_buffers 8 64k;
fastcgi_buffer_size 128k;

client_max_body_size 10m;
client_body_buffer_size 512k;