server {
    listen 80 default_server;
    server_name .dev.srl.local;

    root /var/www/html/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}

# SSL 伺服器配置
# server {
#     listen 443 ssl;
#     server_name _;

#     ssl_certificate /etc/nginx/sslkey/fullchain.pem;
#     ssl_certificate_key /etc/nginx/sslkey/privkey.pem;

#     root /var/www/html/public;
#     index index.php index.html;

#     location / {
#         try_files $uri $uri/ /index.php?$query_string;
#     }

#     location ~ \.php$ {
#         fastcgi_pass app:9000;
#         fastcgi_index index.php;
#         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#         include fastcgi_params;
#     }
# }