/* 建立 develop 使用者 */
CREATE USER IF NOT EXISTS 'develop'@'%' IDENTIFIED BY 'Asdf1q2w3e!';

/* 設定全域權限 */
GRANT ALTER, CREATE, INSERT, SELECT, DELETE, TRIGGER, REFERENCES, UPDATE, DROP, INDEX ON *.* TO 'develop'@'%';
REVOKE CREATE ROUTINE, CREATE VIEW, CREATE USER, SHOW VIEW, ALTER ROUTINE, EVENT, SUPER, RELOAD, FILE, SHOW DATABASES, SHUTDOWN, REPLICATION CLIENT, GRANT OPTION, PROCESS, REPLICATION SLAVE, EXECUTE, LOCK TABLES, CREATE TEMPORARY TABLES ON *.* FROM 'develop'@'%';

/* 更新所有使用者權限 */
FLUSH PRIVILEGES;